
################################################################################
#    &&&....&&&    % Learning R Course in Summer of 2022                       #
#  &&&&&&..&&&&&&  % Teacher: Bo Li, Mingwei Liu                               #
#  &&&&&&&&&&&&&&  % Date: Jul. 28th, 2022                                     #
#   &&&&&&&&&&&&   %                                                           #
#     &&&&&&&&     % Environment: R version 4.1.1;                             #
#       &&&&       % Platform: x86_64-w64-mingw32/x64 (64-bit)                 #
#        &         %                                                           #
################################################################################

################################################################################
### code chunk number 20: Primary drawing in R.
################################################################################

### ****************************************************************************
### Step-01. About working directory in R. 

# 1) For windows, work directory. 

pri.dir <- getwd()

if (!dir.exists("asthma")) dir.create("asthma")

setwd("asthma")

### End of Step-01.
### ****************************************************************************

### ****************************************************************************
### Step-02. Reading the raw data set for GSE470. 

# 1) setting the work directory. 
s <- "GSE470"
setwd(s)
# 2) # reading all files in *.cel format. 
# 3) Normalizing the data. 

### End of Step-02.
### ****************************************************************************

summary(iris)

# 把iris数据集分为两个子数据集，

loc <- sample(1:150, 75, replace = FALSE)

training.set <- iris[loc, ] # 训练集
dim(training.set)

test.set <- iris[-loc, ] # 测试集
dim(test.set)

# 只对训练集进行操作

training.set

table(training.set$Species)

# 建模

library(e1071)
# svm.model1 <- svm(Species ~ ., data = training.set)

# 用训练集建模型

svm.model2 <- svm(x = training.set[, -5], 
                  y = training.set[, 5])

summary(svm.model2)

str(svm.model2)

# 用模型去预测一朵花的类别

pre.label.train <- predict(svm.model2, training.set[, -5])

true.label.train <- training.set[, 5]

table(true.label.train, pre.label.train)

pre.label.test <- predict(svm.model2, test.set[, -5])
true.label.test <- test.set[, 5]

table(true.label.test, pre.label.test)

### ****************************************************************************
### Step-03. Identifying.  

### -------------------------- (2) Wrapper method -------------------------- ###

# Firstly, a gene expression matrix was generated by simulating signals plus noises.  

# 100 genes, 20 samples. 

gem <- matrix(rnorm(20 * 100, sd = 0.3), nrow = 100)

dim(gem) # genes in rows, and samples in columns. 

# Generating the labels os samples. 
labs <- rep(c("Asthma", "Control"), c(10, 10))
print(labs)

gem[1:10, ] # primary expression values for first ten genes. 
gem[1:10, 1:10] <- gem[1:10, 1:10] - 10 # down-regulated genes

gem[11:20, 1:10] <- gem[11:20, 1:10] + 10 # up-regulated genes. 

# iris.gem <- cbind(labs, t(gem))

iris.gem <- data.frame(as.factor(labs), t(gem))

rownames(iris.gem) <- paste("Sample", 1:20, sep = "-")
colnames(iris.gem) <- c("Type", paste("gene", 1:100, sep = "-"))

iris.gem[, 1:21]


## (1) SVM-RFE

library(e1071)

source("D:/00-GitHub/LRC/src/msvmRFE.R")

set.seed(2022)

#---------------------------- first method ----------------------------------###

svmRFE(iris.gem, k = 10, halve.above = 100)

nfold = 10
nrows = nrow(iris.gem)
folds = rep(1:nfold, len=nrows)[sample(nrows)]
results = lapply(folds, svmRFE.wrap, iris.gem, k=5, halve.above=100)
length(results)
top.features = WriteFeatures(results, iris.gem, save=F)
head(top.features)

featsweep = lapply(1:5, FeatSweep.wrap, results, iris.gem)

str(featsweep)

no.info = min(prop.table(table(iris.gem[, 1])))
errors = sapply(featsweep, function(x) ifelse(is.null(x), NA, x$error))

PlotErrors(errors, no.info=no.info)

#---------------------------- Second method ---------------------------------###

library(caret)
set.seed(1)
x <- iris.gem[, -1]
logBBB <- as.factor(labs)
svmProfile <- rfe(x, logBBB,
                  sizes = c(5, 10, 20),
                  rfeControl = rfeControl(functions = caretFuncs,
                                          number = 200),
                  ## pass options to train()
                  method = "svmRadial") # 

svmProfile$variables
str(svmProfile)

### End of Step-02.
### ****************************************************************************

